{
  "/api/admin/productmanagement": {
    "get": {
      "tags": ["Admin - Products"],
      "summary": "Get all products for management",
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "responses": {
        "200": {
          "description": "List of all products",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/AdminProduct"
                }
              }
            }
          }
        },
        "401": {
          "description": "Unauthorized - Invalid or missing token"
        }
      }
    },
    "post": {
      "tags": ["Admin - Products"],
      "summary": "Add new product",
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/AdminProductInput"
            }
          }
        }
      },
      "responses": {
        "201": {
          "description": "Product created successfully",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "productId": {
                    "type": "integer",
                    "example": 1
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}